name: 'Build Docker Image'
description: 'Build a Docker Image for this repository'

inputs:
  image-name:
    description: The image name under which the image is to be stored
    required: true
    default: ${{ github.repository }}
  registry:
    description: The registry the image is being pushed to
    required: true
    default: ghcr.io
  registry-user:
    description: The user pushing the docker image into the registry
    required: true
    default: ${{ github.actor }}
  registry-password:
    description: The password for the user pushing the image to the registry
    required: true

runs:
  using: composite
  
  steps:

    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-*
        merge-multiple: true
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{inputs.image-name}}
      
    - id: registry-login
      name: Login into Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}
      
    - name: Create manifest list and push
      working-directory: /tmp/digests
      shell: bash
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ inputs.registry }}/${{inputs.image-name}}@sha256:%s ' *)   
    
    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.registry }}/${{inputs.image-name}}:${{ steps.meta.outputs.version }} 