name: 'Report Go Test Results to PR'
description: 'Execute Go unit tests and report the results to a pull request'

runs:
  using: "composite"
  steps:
    - id: checkout-repository
      name: Checkout Repository
      uses: actions/checkout@v4

    - id: init-go
      name: Initialize latest stable Go Version
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    - id: install-junit-converter
      name: Install go-junit-report
      shell: bash
      run: go install github.com/jstemmer/go-junit-report/v2@latest

    - id: execute-tests
      name: Execute Test Cases
      shell: bash
      run: go test -v 2>&1 ./... | go-junit-report > report.xml

    - id: build-summary
      name: Build Test Summary
      uses: test-summary/action@v2
      with:
        paths: "report.xml"
        output: summary.md
        show: all
      if: always()

    - id: generate-comment
      name: Generate Comment
      shell: bash
      run: |
        comment=$(cat summary.md)
        echo "COMMENT<<EOF" >> $GITHUB_OUTPUT
        echo $comment >> $GITHUB_OUTPUT 
        echo "EOF" >> $GITHUB_OUTPUT
    
    - id: comment-pr
      name: Write PR Comment
      uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PR_COMMENT: ${{ steps.generate-comment.outputs.comment }}
      with:
        script: |
          const {PR_COMMENT} = process.env
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: PR_COMMENT
          })
    - id: comment-commit
      name: Write Commit Comment
      uses: actions/github-script@v7
      if: ${{ github.event_name != 'pull_request' }}
      env:
        COMMIT_COMMENT: ${{ steps.generate-comment.outputs.comment }}
      with:
        script: |
          const {COMMIT_COMMENT} = process.env
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha
            body: COMMIT_COMMENT
          })
