name: 'Report Go Test Results to PR'
description: 'Execute Go unit tests and report the results to a pull request'

runs:
  using: "composite"
  steps:
    - id: checkout-repository
      name: Checkout Repository
      uses: actions/checkout@v4

    - id: init-go
      name: Initialize latest stable Go Version
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    - id: install-junit-converter
      name: Install go-junit-report
      shell: bash
      run: go install github.com/jstemmer/go-junit-report/v2@latest

    - id: execute-tests
      name: Execute Test Cases
      shell: bash
      run: go test -v ./... | go-junit-report -set-exit-code -subtest-mode exclude-parents -out report.xml

    - id: build-summary
      name: Build Test Summary
      uses: test-summary/action@v2
      with:
        paths: report.xml
        output: summary.md
        show: "fail, skip"
      if: always()

    - id: read-summary
      shell: bash
      run: |
        comment=$(cat summary.md)
        cat summary.md > $GITHUB_STEP_SUMMARY
        echo "SUMMARY<<EOF" >> $GITHUB_OUTPUT
        echo $comment >> $GITHUB_OUTPUT 
        echo "EOF" >> $GITHUB_OUTPUT
         
    
    - id: comment-pr
      name: Write PR Comment
      uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      env:
        SUMMARY: ${{ steps.read-summary.outputs.summary }}
      with:
        script: |
          const {SUMMARY} = process.env
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: SUMMARY
          })

    - id: comment-commit
      name: Write Commit Comment
      uses: actions/github-script@v7
      if: ${{ github.event_name != 'pull_request' }}
      env:
        SUMMARY: ${{ steps.read-summary.outputs.summary }}
      with:
        script: |
          const {SUMMARY} = process.env
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: SUMMARY
          })
