name: 'Build Docker Image'
description: 'Build a Docker Image for this repository'

inputs:
  image-name:
    description: The image name under which the image is to be stored
    required: true
    default: ${{ github.repository }}
  registry:
    description: The registry the image is being pushed to
    required: true
    default: ghcr.io
  registry-user:
    description: The user pushing the docker image into the registry
    required: true
    default: ${{ github.actor }}
  registry-password:
    description: The password for the user pushing the image to the registry
    required: true
  cache-path:
    description: The paths that shall be cached inbetween builds
    required: false
  cache-map:
    description: The mapping for mounting the caches into the containers
    required: false
  cache-key:
    description: A caching key that may be used to cache reproducible build artifacts
    required: false

runs:
  using: composite
  
  steps:
    - id: checkout
      name: Checkout Build Sources
      uses: actions/checkout@v4

    - id: git-info
      name: Collect Git Info
      shell: bash
      run: |
        echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
        echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "commit_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "commit_message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
        echo "commit_date=$(git log -1 --date=iso --pretty=%cd)" >> $GITHUB_OUTPUT
        echo "status=$(git status --short | sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_OUTPUT

    - id: qemu-setup
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - id: setup-docker-buildx
      name: Setup BuildX for Docker
      uses: docker/setup-buildx-action@v3

    - id: registry-login
      name: Login into Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-password }}
    
    - id: docker-metadata
      name: Configure Metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{inputs.image-name}}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}},priority=3000
          type=ref,event=tag,priority=2500
          type=ref,event=branch,priority=2000
          type=sha,prefix=,priority=1000

    - id: build-cache
      name: Build Cache for Docker
      uses: actions/cache@v4
      if: ${{ inputs.cache-key != ''  && inputs.cache-path != '' && inputs.cache-map != '' }}
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}

    - id: inject-cache
      name: Inject BuildKit Caches
      uses: reproducible-containers/buildkit-cache-dance@v3
      if: ${{ inputs.cache-key != ''  && inputs.cache-path != '' && inputs.cache-map != '' }}
      with:
        cache-map: ${{ inputs.cache-map }}
        skip-extraction: ${{ steps.build-cache.outputs.cache-hit }}

    - id: build-and-push-image
      name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker-metadata.outputs.tags }}
        labels: ${{ steps.docker-metadata.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args:
          - GIT_BRANCH=${{ steps.git-info.outputs.branch }}
          - GIT_COMMIT_SHA=${{ steps.git-info.outputs.commit_sha }}
          - GIT_COMMIT_SHORT=${{ steps.git-info.outputs.commit_short }}
          - GIT_COMMIT_MESSAGE=${{ steps.git-info.outputs.commit_message }}
          - GIT_COMMIT_DATE=${{ steps.git-info.outputs.commit_date }}
          - GIT_STATUS=${{ steps.git-info.outputs.status }}
